export const menuItems = [
  {
    id: 1,
    name: "Chapati / Bhakri",
    nameMr: "चपाती / भाकरी",
    nameHi: "रोटी / भाकरी",
    category: "veg",
    description: "Soft, hot phulkas or traditional rustic bhakri.",
    descMr: "मऊ, गरम फुलके किंवा पारंपारिक भाकरी.",
    descHi: "मुलायम, गरमागरम फुल्के या पारंपरिक भाकरी।",
    image: "https://images.unsplash.com/photo-1626200419109-3221ac077c57?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 2,
    name: "Varan Bhaat",
    nameMr: "वरण भात",
    nameHi: "दाल चावल (वरन भात)",
    category: "veg",
    description: "Comforting dal over steamed rice with a dollop of pure ghee.",
    descMr: "साजूक तूप घातलेला गरमागरम वरण भात.",
    descHi: "गरमागरम दाल चावल शुद्ध देशी घी के साथ।",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 3,
    name: "Patal Bhaji",
    nameMr: "पातळ भाजी",
    nameHi: "रस्सेदार सब्जी",
    category: "veg",
    description: "Authentic Maharashtrian liquid dry vegetable curry.",
    descMr: "पारंपारिक मराठमोळी पातळ भाजी.",
    descHi: "पारंपरिक महाराष्ट्रीयन रस्सेदार सब्जी।",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 4,
    name: "Sukhi Bhaji",
    nameMr: "सुकी भाजी",
    nameHi: "सूखी सब्जी",
    category: "veg",
    description: "Dry, spiced vegetable preparation of the day.",
    descMr: "दररोजची चविष्ट आणि मसालेदार सुकी भाजी.",
    descHi: "रोज की स्वादिष्ट और मसालेदार सूखी सब्जी।",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 5,
    name: "Masale Bhaat",
    nameMr: "मसाले भात",
    nameHi: "मसाला चावल",
    category: "veg",
    description: "Traditional spicy Maharashtrian seasoned rice.",
    descMr: "पारंपारिक मसालेदार आणि चविष्ट मसाले भात.",
    descHi: "पारंपरिक मसालेदार और स्वादिष्ट मसाला चावल।",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 6,
    name: "Upvas Khichdi",
    nameMr: "उपवासाची खिचडी",
    nameHi: "उपवास साबूदाना खिचड़ी",
    category: "veg",
    description: "Sabudana Khichdi, perfectly crafted for fasting days.",
    descMr: "उपवासासाठी खास बनवलेली साबुदाणा खिचडी.",
    descHi: "उपवास के लिए खास तौर पर बनाई गई साबूदाना खिचड़ी।",
    image: "https://images.unsplash.com/photo-1688647582531-2f74154bcfae?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 7,
    name: "Pithla Bhakri",
    nameMr: "पिठलं भाकरी",
    nameHi: "पिठला भाकरी",
    category: "veg",
    description: "The classic farmer's meal, rich in flavor and nutrition.",
    descMr: "गावरान चवीचं अस्सल पिठलं आणि भाकरी.",
    descHi: "देसी स्वाद वाला पारंपरिक पिठला और भाकरी।",
    image: "https://images.unsplash.com/photo-1626544827763-d516dce335e2?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 14,
    name: "Pav Bhaji",
    nameMr: "पाव भाजी",
    nameHi: "पाव भाजी",
    category: "veg",
    description: "Spicy, buttery vegetable mash served with soft pav.",
    descMr: "चमचमीत आणि खमंग पाव भाजी सोबत मऊ पाव.",
    descHi: "स्वादिष्ट और मक्खन से भरपूर पाव भाजी और मुलायम पाव।",
    image: "https://images.unsplash.com/photo-1628126235206-5260b9ea6441?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 15,
    name: "Salad",
    nameMr: "कोशिंबीर",
    nameHi: "सलाद",
    category: "veg",
    description: "Freshly sliced cucumbers, tomatoes, onions and lemon.",
    descMr: "ताजी काकडी, टोमॅटो आणि कांद्याची कोशिंबीर.",
    descHi: "ताजा खीरा, टमाटर और प्याज का सलाद।",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800",
  },
  // Non-Veg
  {
    id: 8,
    name: "Egg Curry",
    nameMr: "अंडा करी",
    nameHi: "अंडा करी",
    category: "non-veg",
    description: "Spicy and rich egg curry with homestyle spices.",
    descMr: "घरगुती मसाल्यात बनवलेली झणझणीत अंडा करी.",
    descHi: "घरेलू मसालों से बनी स्वादिष्ट अंडा करी।",
    image: "https://images.unsplash.com/photo-1614569344158-b6151475c400?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 16,
    name: "Egg Poli",
    nameMr: "अंडा पोळी",
    nameHi: "अंडा पराठा",
    category: "non-veg",
    description: "Classic Maharashtrian egg omelette cooked perfectly inside a flatbread.",
    descMr: "चविष्ट आणि गरमागरम पोळीमध्ये बनवलेले ऑम्लेट.",
    descHi: "पूरी तरह से पकाया गया क्लासिक महाराष्ट्रीयन अंडा पराठा।",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 9,
    name: "Spicy Chicken",
    nameMr: "झणझणीत चिकन",
    nameHi: "मसालेदार चिकन",
    category: "non-veg",
    description: "Zhanzhanit chicken cooked in robust traditional masalas.",
    descMr: "अस्सल गावरान मसाल्यातील झणझणीत चिकन.",
    descHi: "पारंपरिक मसालों में पकाया गया मसालेदार चिकन।",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 10,
    name: "Sunday Special Sweet",
    nameMr: "रविवार विशेष गोड बातमी",
    nameHi: "रविवार स्पेशल मिठाई",
    category: "non-veg",
    description: "A delightful sweet addition to your Sunday non-veg feast.",
    descMr: "तुमच्या रविवारच्या मांसाहारी भोजनासोबत गोड पदार्थ.",
    descHi: "रविवार के मांसाहारी भोजन के साथ खास मिठाई।",
    image: "https://images.unsplash.com/photo-1589301760014-a929f539b1a5?auto=format&fit=crop&q=80&w=800",
  },
  // Special
  {
    id: 11,
    name: "Puran Poli",
    nameMr: "पुरणपोळी",
    nameHi: "पूरन पोली",
    category: "special",
    description: "Sweet flatbread loaded with ghee, melting in the mouth.",
    descMr: "तोंडात विरघळणारी आणि साजूक तुपातील गोड पुरणपोळी.",
    descHi: "मुंह में पिघलने वाली शुद्ध देसी घी युक्त मीठी पूरन पोली।",
    image: "https://images.unsplash.com/photo-1662057393282-53def79402c5?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 12,
    name: "Sheera",
    nameMr: "शिरा",
    nameHi: "सूजी का हलवा",
    category: "special",
    description: "Divine semolina sweet roasted in pure ghee and dry fruits.",
    descMr: "सुकामेवा आणि साजूक तुपात भाजलेला गोड शिरा.",
    descHi: "शुद्ध घी और मेवों में भूना हुआ सूजी का हलवा।",
    image: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 13,
    name: "Festival Special Meals",
    nameMr: "सण विशेष भोजन",
    nameHi: "त्यौहार स्पेशल भोजन",
    category: "special",
    description: "Complete feast packages curated specifically for festivals.",
    descMr: "सणांसाठी खास बनवलेले संपूर्ण भोजन थाळी.",
    descHi: "त्यौहारों के लिए खास तौर पर तैयार की गई संपूर्ण थाली।",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 17,
    name: "Special Chicken Thali",
    nameMr: "स्पेशल चिकन थाळी",
    nameHi: "स्पेशल चिकन थाली",
    category: "special",
    description: "A grand authentic Maharashtrian chicken thali for special occasions.",
    descMr: "विशेष दिवसांसाठी अस्सल मराठमोळी भव्य चिकन थाळी.",
    descHi: "खास दिनों के लिए एक भव्य पारंपरिक महाराष्ट्रीयन चिकन थाली।",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=800",
  }
];

export const serviceAreas = [
  "Shanivar Peth",
  "Narayan Peth",
  "Kasba Peth",
  "Sadashiv Peth"
];
